name: wordpress.org deploy
on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: On dry-run mode
      version:
        type: string
        description: Version tag
#  push:
#    tags:
#      - "*"
jobs:
  tag:
    name: Releasing new version on wordpress.org plugin repository
    runs-on: ubuntu-latest
    steps:
      - name: Installing WP-CLI
        uses: godaddy-wordpress/setup-wp-cli@1
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build Plugin
        run: |
          composer install --no-dev
          npm install
          npm run build
          npm run makepot
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: ${{ github.event.inputs.dry_run }}
      - name: Build ZIP
        uses: 10up/action-wordpress-plugin-build-zip@stable
        with:
          retention-days: 2
        env:
          SVN_PASSWORD: ${{ secrets.SVN_WCP_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_WCP_USERNAME }}
          SLUG: wc-call-for-price
          VERSION: ${{ github.event.inputs.version }}
